# docker-compose -p microservices-assignment -f docker-compose.yml up -d
services:

  # PostgreSQL for Room Service
  postgres-room-service:
    image: postgres:latest
    ports:
      - "5442:5432"
    container_name: postgres-room-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/room-service:/var/lib/postgresql/data
      - ./init/room-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  # PostgreSQL for User Service
  postgres-user-service:
    image: postgres:latest
    ports:
      - "5443:5432"
    container_name: postgres-user-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/user-service:/var/lib/postgresql/data
      - ./init/user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  # pgAdmin for PostgreSQL Management
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8888:80"
    container_name: pgadmin-single
    environment:
      PGADMIN_DEFAULT_EMAIL: a1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - spring

  # Booking Service
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    container_name: booking-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  # Event Service
  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    container_name: event-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  # Approval Service
  approval-service:
    build:
      context: ./approval-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    container_name: approval-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  # MongoDB for NoSQL Services
  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - spring

  # Mongo Express for MongoDB Management
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    container_name: mongo-express-a
    depends_on:
      - mongodb
    networks:
      - spring

volumes:
  mongo-db:
    driver: local

networks:
  spring:
    driver: bridge
