#version: '3.9'
#
#services:
#
#  postgres-room-service:
#    image: postgres
#    ports:
#      - "5442:5432"
#    container_name: postgres-room-service
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - ./data/room-service:/var/lib/postgresql/data
#      - ./init/room-service/init.sql:/docker-entrypoint-initdb.d/init.sql
#
#  postgres-user-service:
#    image: postgres
#    ports:
#      - "5443:5432"
#    container_name: postgres-user-service
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - ./data/user-service:/var/lib/postgresql/data
#      - ./init/user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
#
#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - "8888:80"
#    container_name: pgadmin-single
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=a1@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=password